palette = "catppuccin_frappe"
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$docker_context\
$line_break\
$jobs\
$character"""

[directory]
style = "blue"
truncation_length = 4
truncate_to_repo = false 
truncation_symbol = '.../'
before_repo_root_style = 'blue'
repo_root_style = 'lavender'
# repo_root_format = "[$repo_root][$path]"
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[jobs]
format = "[$number$symbol ](blue)"
symbol = ' î®¢'
# threshhold = 1
# number_threshold = 3
# symbol_threshold = 1

[character]
success_symbol = "[ ïˆ… ](blue)"
error_symbol = "[ ïˆ„ ](maroon)"
vimcmd_symbol = "[ ïˆ„ ](blue)"
vimcmd_visual_symbol = "[ îš¬ ](sapphire)"
vimcmd_replace_symbol = "[ ó°°Ÿ](red)"

[git_branch]
format = "[$branch ]($style)"
style = "bright-black"


[git_status]
format = "[[$staged](teal)[($conflicted$untracked$modified$staged)](peach) ($ahead$behind$stashed)]($style)"
style = "cyan"
ahead = 'â‡¡'
behind = 'â‡£'
untracked = ''
staged = '+'
conflicted = "ï“› "
# untracked = "ï“› "
modified = " *"
diverged = "â‡• "
# # staged = "â€‹"
# # renamed = "â€‹"
# # deleted = "â€‹"
 # stashed = "ó°˜“"
  stashed = " ó°œ¦"

[git_state]
format = '\([$state( $progress_current/$progress_total)$rebase$revert$bisect]($style)\) '
rebase = 'REBASING'
revert = 'REVERTING'
bisect = 'BISECTING'
style = "bright-black"

# [cmd_duration]
# format = "[$duration]($style) "
# style = "yellow"

[python]
symbol = "îˆµ "
format = "[$virtualenv]($style) "
style = "bright-black"


# [docker_context]
# symbol = "ïŒˆ "
[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[aws]
symbol = "îŒ½  "

[conda]
symbol = "ï„Œ "


[golang]
symbol = "î˜§ "

[hostname]
ssh_symbol = "î¬ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ó°› "

[nodejs]
symbol = "îœ˜ "

[os.symbols]
Amazon = "ï‰° "
Android = "ï…» "
Fedora = "ïŒŠ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[package]
symbol = "ó°— "

[rust]
symbol = "î¨ "

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
